### ISSUE TITLE
How to run with your src

### ISSUE THREAD

**Issue by owenchen** [irvingc/dbscan-on-spark#1]
Hi 
I just found your git right now. 
The readme for programmer is good. If the user want to run your the compiled jar file. Can you give me a example in command line.
Like, 
spark-submit --class org.apache.spark.mllib.clustering.dbscan target/dbscan-on-spark_2.10-0.2.0-SNAPSHOT.jar <input> <eps> <minPts> 

Thanks

**Comment by irvingc** [comment]
I think this is no longer relevant, closing, let me know if you still need help
