### ISSUE TITLE
A small bug in README.md

### ISSUE THREAD

**Issue by hi-T0day** [irvingc/dbscan-on-spark#7]
> resolvers += "bintray/irvingc" at "http://dl.bintray.com/irvingc/maven"
>libraryDependencies += "com.irvingc.spark" %% "dbscan" % "0.1.0"

I think the last line should be change to 
libraryDependencies += "com.irvingc.spark" %% "dbscan_2.10" % "0.1.0"

Add "_2.10"

**Comment by sergeyjsg** [comment]
No, actually `%%` means `add your current version of scala to library name`. And `%` means `no substitute`, So `"com.irvingc.spark" %% "dbscan"` equals to `"com.irvingc.spark" % "dbscan_2.10"`

**Comment by irvingc** [comment]
@hi-T0day, @sergeyjsg is correct, see [here](http://www.scala-sbt.org/1.x/docs/Library-Dependencies.html) for reference. Thanks @sergeyjsg .
